version: '3.7'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: mapdata-sonarqube
    ports:
      - "83:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres-sonar:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonarqube-net
    depends_on:
      - postgres-sonar
    restart: always

  postgres-sonar:
    image: postgres:13
    container_name: postgres-sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sonarqube-net
      - mapdata-network
    restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:

networks:
  sonarqube-net:
    driver: bridge
  mapdata-network:
    external: true