version: '3.7'

services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    ports:
      - "81:8080"
    environment:
      - ATL_JIRA_HOME=/var/atlassian/application-data/jira
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=2048m
    volumes:
      - jira_home:/var/atlassian/application-data/jira
    networks:
      - jira-net
      - mapdata-network
    restart: always

volumes:
  jira_home:

networks:
  jira-net:
    driver: bridge
  mapdata-network:
    external: true