#spring.datasource.url= jdbc:postgresql://postgres_container:5432/sampledb
spring.datasource.url= jdbc:postgresql://ec2-54-246-1-94.eu-west-1.compute.amazonaws.com:5432/d67umkgcfs9kfm
spring.datasource.username= lichvkzqdmrdgg
spring.datasource.password= c16c260235345773d6e544a3ab557112cb8dfab72a9ba67af7b7c57e48a2182b

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver