version: "3.8"

services:
  mapdata-app:
    container_name: mapdata-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "4200:80"
    networks:
      - mapdata-network

networks:
  mapdata-network:
    external: true
