version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "82:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/opt/keycloak/init-realm.json
    volumes:
      - ./keycloak-realm:/opt/keycloak/init-realm.json
    networks:
      - keycloak-net
      - mapdata-network
    restart: always

networks:
  keycloak-net:
    driver: bridge
  mapdata-network:
    external: true