version: '3.8'

services:
  mapdata-db:
    image: postgres:17
    container_name: mapdata_db_container
    environment:
      POSTGRES_USER: mapdata_admin_user
      POSTGRES_PASSWORD: mapdata_admin_pwd
      POSTGRES_DB: mapdata_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mapdata-network

volumes:
  postgres_data:
    name: mapdata_db_volume
    
networks:
  mapdata-network: 
    name: mapdata-network