version: '3.1'

services:
  mapdata-db:
    container_name: mapdata-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: joaofaria_user
      POSTGRES_PASSWORD: my_pwd_123
      POSTGRES_DB: mapdata_db
    ports:
      - "5432:5432"
    volumes:
      - mapdata_volume:/var/lib/postgresql/data
    networks:
      - mapdata-network

volumes:
  mapdata_volume:

networks:
   mapdata-network:
      external: true
